#!/bin/bash

set -euo pipefail
VENV_NAME=".venv"

if [ ! -e "${VENV_NAME}" ]; then
    sudo rfkill unblock bluetooth
    python -m venv "${VENV_NAME}"
    source ${VENV_NAME}/bin/activate
    pip install pyserial
    deactivate
fi
